service: message-channel

package:
  exclude:
    - "README.md"

provider:
  name: aws
  runtime: python2.7
  stage: dev
  environment:
    SNS_TOPIC_ARN_PREFIX: ${self:custom.snsTopicArnPrefix}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'SNS:Publish'
      Resource:
        Fn::Join:
          - ":"
          - - ${self:custom.snsTopicArnPrefix}
            - "*"

custom:
  snsTopicArnPrefix:
    Fn::Join:
      - ":"
      - - "arn:aws:sns"
        - Ref: AWS::Region
        - Ref: AWS::AccountId

functions:
  send-message:
    handler: handler.send_message
    events:
      - http:
          path: message-channel/send
          method: post
  receive-message:
    handler: handler.receive_message
    events:
      - sns:
          topicName: 'message-channel'
          displayName: "An example message channel"
