service: message-channel

package:
  exclude:
    - "README.md"

provider:
  name: aws
  runtime: python2.7
  stage: dev
  environment:
    MESSAGE_CHANNEL_NAME:
      'Fn::ImportValue': 'infrastructure:${opt:stage, self:provider.stage}:MessageChannel'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'Kinesis:PutRecord'
      Resource:
        'Fn::ImportValue': 'infrastructure:${opt:stage, self:provider.stage}:MessageChannelArn'

functions:
  send-message:
    handler: handler.send_message
    events:
      - http:
          path: message-channel/send
          method: post
  receive-message:
    handler: handler.receive_message
    events:
      - stream:
          type: kinesis
          arn:
            'Fn::ImportValue': 'infrastructure:${opt:stage, self:provider.stage}:MessageChannelArn'
