service: infrastructure

provider:
  name: aws
  runtime: python2.7
  stage: dev

resources:
  Resources:
    MessageChannel:
      Type: AWS::Kinesis::Stream
      Properties:
        ShardCount: 1
  Outputs:
     Channel:
       Description: "Message channel"
       Value:
         Ref: MessageChannel
       Export:
         Name: '${self:service}:${opt:stage, self:provider.stage}:MessageChannel'
     ChannelArn:
       Description: "Message channel ARN"
       Value:
         Fn::GetAtt:
           - MessageChannel
           - Arn
       Export:
         Name: '${self:service}:${opt:stage, self:provider.stage}:MessageChannelArn'
